baseURL = 'https://akshayuppal.github.io/'
languageCode = 'en-us'
title = 'Akshay Uppal'
theme = 'PaperMod'

[pagination]
  pagerSize = 5

[params]
  description = "Welcome to my blog where I post all things ML - code, blogs, paper annotations, and more."
  author = "Akshay Uppal"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  defaultTheme = "dark"  # Dark theme by default

  [params.profileMode]
    enabled = true
    title = "Akshay Uppal"
    subtitle = "Machine Learning Engineer | ML Research | Making ML Accessible"
    imageUrl = "/images/bio-photo.png"
    imageTitle = "Profile"

    [[params.profileMode.buttons]]
      name = "Posts"
      url = "/posts/"
    [[params.profileMode.buttons]]
      name = "Categories"
      url = "/categories/"
    [[params.profileMode.buttons]]
      name = "About"
      url = "/about/"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/uppalakshay/"
  [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/akshayuppal12"
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/akshayuppal"
  [[params.socialIcons]]
    name = "instagram"
    url = "https://instagram.com/akshay_uppal12"

  [params.analytics.google]
    SiteVerificationTag = "G-3B9WV5JCK6"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 20
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 30
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 40
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 50

[outputs]
  home = ["HTML", "RSS", "JSON"]  # Enable JSON for search

[taxonomies]
  category = "categories"
  tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Allow raw HTML in markdown (needed for embedded PDFs and HTML content)
